# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('we_help', '0002_auto_20180228_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images/event')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='we_help.Event'),
        ),
    ]
