# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_help', '0003_auto_20180401_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='is_pick_up',
            field=models.TextField(default='no', max_length=10),
        ),
    ]
