# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, default='', upload_to='images/pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic_id',
            field=models.FileField(blank=True, default='', upload_to='images/pic_id'),
        ),
    ]
